name: Create Pull Request for Upstream Changes

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Git
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Add upstream remote
      run: git remote add upstream https://github.com/berachain/polaris.git

    - name: Fetch upstream changes
      run: git fetch upstream

    - name: Checkout a new branch for upstream changes
      run: |
        git checkout -b update-upstream-$(date +%Y-%m-%d)

    - name: Merge upstream changes
      run: git merge upstream/main --no-commit --no-ff

    - name: Commit changes
      run: |
        git commit -m "Merge upstream changes"
        git push origin HEAD

    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "develop"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Merge upstream changes"
        pr_body: "Automatically created by GitHub Actions"
